### PR TITLE
Fix issue with check_config and set prefix.

### LINKED ISSUE #39: The check_configs function only works with one update config.
The "name" parameter is a hardcoded string called from create_updates so it will always go to this if:
```
        def check_configs(name, configs):
            if isinstance(name, string_types):
                logging.debug("Handling %s as JSON string.", name)
                try:
                    configs = json.loads(configs)
                except:
                    raise Exception("{name} is invalid JSON!".format(name=name))
                configs = [configs]
```
The "configs" variable can only be one dict for json.loads unless you put it in a list, but if you do, the configs list is then deposited into another list.

### PR DESCRIPTION
**Pull request by miott**
Fixes #39 

String check on name instead of config that may be json.

Passing in prefix to set() fails because in order to set a prefix you must "CopyFrom" not assign.

Added a logger for clients to be able to see the string representation of the gnmi messages in logs for debugging..

### CODE REVIEW

**Comment by miott** [comment]
BTW, can we decorate Client.parse_xpath_to_gnmi_path() with \@classmethod?  Handy utility.

**Comment by remingtonc** [comment]
Logger messages reinforcing #38 - we should have an easy way to dump all protos throughout construction.

**Comment by remingtonc** [comment]
Added logging to everything. Good idea.

**Review by remingtonc — APPROVED** [review]
Thank you!

**Pull request merged**
