### PR TITLE
Add several examples

### LINKED ISSUE #40: Suggest examples in the README (or Wiki).
I could use an example of how to formulate a Subscription.

Suggestion for documentation:
For the README or WiKi, I'd suggest something like the following:
# Working example of OpenConfig Streaming Telemetry on Aceess Point.
from cisco_gnmi import ClientBuilder

builder = ClientBuilder('192.168.0.5:8080')
builder.set_secure_from_target()
builder.set_ssl_target_override('openconfig.mojonetworks.com')
builder.set_call_authentication('admin', 'admin')
client = builder.construct()

paths = [client.parse_xpath_to_gnmi_path('/access-points/access-point[hostname="test-ap.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/')]
print(client.get(paths))

You may also want to provide a pointer in your documentation that list-key values must be quoted due to your xpath parsing. Even if the list-key is an int (like the radio id in the above example).

### PR DESCRIPTION
**Pull request by remingtonc**
Add several example scripts under `examples/` which utilize the library for various purposes.

* `subscribe_dump.py` Subscribes and `SAMPLE`s a network element and dumps to a file.
* `subscribe_onchange.py` Subscribes `ON_CHANGE` to a network element and dumps to a file.
* `load_subscribe_dump.py` just demonstrates how to load textual/json/dumped protos from a file.
* `custom.py` does not utilize one of the wrappers and manually manipulates protos.

Fixes #40

### CODE REVIEW

**Comment by remingtonc** [comment]
@mike-albano Does this address any of your questions?

**Comment by mike-albano** [comment]
Gave it a shot. Have not looked into what the different OS' mean (guessing different Cisco OS' implement gNMI differently?) but it looks like None is not acceptable:

```
python3 subscribe_dump.py -xpath '/access-points/access-point[hostname="foo.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/' '192.168.0.31:8080' -no_stop -os None
usage: subscribe_dump.py [-h] [-os {None,IOS XR,NX-OS,IOS XE}] [-xpath XPATH]
                         [-protos_file PROTOS_FILE] [-no_stop]
                         [-encoding [ENCODING]] [-text_format] [-raw_json]
                         netloc
subscribe_dump.py: error: argument -os: invalid choice: 'None' (choose from None, 'IOS XR', 'NX-OS', 'IOS XE')
```
Looks like [this](https://github.com/cisco-ie/cisco-gnmi-python/blob/master/src/cisco_gnmi/builder.py#L130) is where that's catching.

Tried custom.py as well, after removing "data_type="STATE"," from get_response variable:
```
python3 custom.py
Host/Port: 192.168.0.31:8080
Username: admin
Password:
WARNING:root:Overriding SSL option from certificate could increase MITM susceptibility!
Press Enter for Capabilities...
supported_models {
  name: "anet-ap"
  organization: "Arista Networks Inc."
  version: "0.1.0"
}
supported_encodings: JSON
supported_encodings: JSON_IETF
gNMI_version: "0.7.0"

Press Enter for Get...
notification {
  timestamp: 1585939544391066400
  update {
    path {
      elem {
        name: "access-points"
      }
      elem {
        name: "access-point"
        key {
          key: "hostname"
          value: "albano-house.example.net"
        }
      }
      elem {
        name: "radios"
      }
      elem {
        name: "radio"
        key {
          key: "id"
          value: "0"
        }
      }
      elem {
        name: "state"
      }
      elem {
        name: "rx-noise-channel-utilization"
      }
    }
    val {
      uint_val: 0
    }
  }
}

Press Enter for Subscribe SAMPLE...
Traceback (most recent call last):
  File "custom.py", line 80, in <module>
    subscription_list.subscription.append(sampled_subscription)
AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'append'
```

Happy to debug further; or ping you some creds/targets if you'd prefer to have direct access to this gNMI Target (an Arista WiFi AP).

**Comment by remingtonc** [comment]
Ah @mike-albano  on the `append` issue, older versions of the `protobuf` library don't have `append` for lists only `extend`. https://github.com/cisco-ie/cisco-gnmi-python/pull/30
Changed to use `extend`, should work now (it's what the library uses as well).

Added an explicit `None` as an OS alias, as well as `XR`, `XE`, and `NX`.

**Comment by mike-albano** [comment]
```
python3 subscribe_dump.py -xpath '/access-points/access-point[hostname="albano-house.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/' '192.168.0.31:8080' -no_stop -os "None"
usage: subscribe_dump.py [-h] [-os {None,IOS XR,NX-OS,IOS XE}] [-xpath XPATH]
                         [-protos_file PROTOS_FILE] [-no_stop]
                         [-encoding [ENCODING]] [-text_format] [-raw_json]
                         netloc
subscribe_dump.py: error: argument -os: invalid choice: 'None' (choose from None, 'IOS XR', 'NX-OS', 'IOS XE')

python3 subscribe_dump.py -xpath '/access-points/access-point[hostname="albano-house.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/' '192.168.0.31:8080' -no_stop -os None
usage: subscribe_dump.py [-h] [-os {None,IOS XR,NX-OS,IOS XE}] [-xpath XPATH]
                         [-protos_file PROTOS_FILE] [-no_stop]
                         [-encoding [ENCODING]] [-text_format] [-raw_json]
                         netloc
subscribe_dump.py: error: argument -os: invalid choice: 'None' (choose from None, 'IOS XR', 'NX-OS', 'IOS XE')
```

Looks like subscribe_dump is [calling a function](https://github.com/cisco-ie/cisco-gnmi-python/pull/46/files#diff-5a9fc16c73d2f9a805c5c154588e4bdfR54) not in client.py, though that is in the os-specific libraries.

**Comment by mike-albano** [comment]
Here's the appropriate output for the subscribe error. The OS issue is resolved per your last commit:
```
python3 subscribe_dump.py -xpath '/access-points/access-point[hostname="test.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/' '192.168.0.31:8080' -os None -no_stop
Username: admin
Password:
INFO:root:Connecting to 192.168.0.31:8080 as None ...
WARNING:root:Overriding SSL option from certificate could increase MITM susceptibility!
INFO:root:Subscribing to /access-points/access-point[hostname="albano-house.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/ ...
ERROR:root:Stopping due to exception!
Traceback (most recent call last):
  File "subscribe_dump.py", line 54, in main
    for message in client.subscribe_xpaths(**sub_args):
AttributeError: 'Client' object has no attribute 'subscribe_xpaths'
INFO:root:Writing to gnmi_sub.json ...
```

**Comment by remingtonc** [comment]
@mike-albano `subscribe_xpaths` should now be available in the base `Client` and resolve your usage issue.

**Comment by mike-albano** [comment]
Yep, that's resolved, thanks. Not sure if you want to overlad this GitHub Issue w/ this tshooting (lmk if you want new issues instead) but here's how far I'm getting at this point:

If I'm interpreting this correctly, the -no_stop should continually dump, however rpc terminating with EOF.
```
python3 subscribe_dump.py -xpath '/access-points/access-point[hostname="albano-house.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/' '192.168.0.31:8080' -os None
Username: admin
Password:
INFO:root:Connecting to 192.168.0.31:8080 as None ...
WARNING:root:Overriding SSL option from certificate could increase MITM susceptibility!
INFO:root:Subscribing to /access-points/access-point[hostname="albano-house.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/ ...
INFO:root:{'update': {'timestamp': '1587091884807946240', 'update': [{'path': {'elem': [{'name': 'access-points'}, {'name': 'access-point', 'key': {'hostname': 'albano-house.example.net'}}, {'name': 'radios'}, {'name': 'radio', 'key': {'id': '0'}}, {'name': 'state'}, {'name': 'rx-noise-channel-utilization'}]}, 'val': {'uintVal': '0'}}]}}
ERROR:root:Stopping due to exception!
Traceback (most recent call last):
  File "subscribe_dump.py", line 56, in main
    for message in client.subscribe_xpaths(**sub_args):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/grpc/_channel.py", line 347, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "EOF"
	debug_error_string = "{"created":"@1587091885.760523000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"EOF","grpc_status":2}"
>
INFO:root:Writing to gnmi_sub.json ...
```
And gnmi_sub.json does contain that first response as in the output above.

**Comment by remingtonc** [comment]
Let's do a separate issue for this, as I'm not convinced it's client related. It looks like something on the server side, but I'd be happy to be wrong as well if there's some kind of EOF behavior for gRPC/gNMI to be handled.

**Comment by mike-albano** [comment]
Agreed. Opened Issue #49

**Review by brh55 — APPROVED** [review]
Great examples.

**Comment by anushramsurat1** [comment]
Solid examples. Great work!

**Pull request merged**
