### PR TITLE
Add cli.py as cisco-gnmi to demonstrate cisco_gnmi usage

### LINKED ISSUE #37: Doc specifies iterable for Client methods but requires list/set
We  should accept any Iterable ([or iterator?](https://docs.python.org/2.7/glossary.html#term-iterator)).

e.g.
https://github.com/cisco-ie/cisco-gnmi-python/blob/0262b78a3098ab8c2794b5bb68dad3dde6ea96f3/src/cisco_gnmi/client.py#L155

### LINKED ISSUE #40: Suggest examples in the README (or Wiki).
I could use an example of how to formulate a Subscription.

Suggestion for documentation:
For the README or WiKi, I'd suggest something like the following:
# Working example of OpenConfig Streaming Telemetry on Aceess Point.
from cisco_gnmi import ClientBuilder

builder = ClientBuilder('192.168.0.5:8080')
builder.set_secure_from_target()
builder.set_ssl_target_override('openconfig.mojonetworks.com')
builder.set_call_authentication('admin', 'admin')
client = builder.construct()

paths = [client.parse_xpath_to_gnmi_path('/access-points/access-point[hostname="test-ap.example.net"]/radios/radio[id="0"]/state/rx-noise-channel-utilization/')]
print(client.get(paths))

You may also want to provide a pointer in your documentation that list-key values must be quoted due to your xpath parsing. Even if the list-key is an int (like the radio id in the above example).

### PR DESCRIPTION
**Pull request by remingtonc**
Inspired by `flask`. Adds a `cisco-gnmi` command supporting usage of `Capabilities`, `Get`, `Set` and `Subscribe`. ~`Set` has not been properly tested and should gate this pull request. Opening for the sake of review.~

Related to #40 
Fixes #37

### CODE REVIEW

**Review by byzek — COMMENTED** [review]
Why gnmcli and not gnmicli or gnmi-cli? I think that's going to mess people up.

Also, add example output for each command.

**Comment by miott** [comment]
I have added something similar to this in the yang.connector library.
https://github.com/CiscoTestAutomation/yang/blob/master/connector/src/yang/connector/gnmi.py
Look at "Standalone Examples (pyATS not installed):"
This does require the pull request changes I have open now. #44 
Can we have a code review meeting on those changes?  A lot going on there but I do need this type of functionality in soon in order to get the teams working on gNMI automation testing.

**Comment by remingtonc** [comment]
> Why gnmcli and not gnmicli or gnmi-cli? I think that's going to mess people up.
> 
> Also, add example output for each command.

@byzek [`gnmi_cli`](https://github.com/openconfig/gnmi/tree/master/cmd/gnmi_cli) and [`py_gnmicli`](https://github.com/google/gnxi/tree/master/gnmi_cli_py) are taken respectively, and I liked `gRPC Network Management [Command Line] Interface (gnmcli)`. But I am open to changing to another naming convention, albeit if we do I'm inclined to say it should be `cisco-gnmi` as the command name.

@miott I was reviewing yesterday and deciphering what was happening - you're thinking about things differently than I am (likely more YANG & friends knowledge) so yes let's sync today, something will be on your calendar shortly.

**Review by brmcdoug — APPROVED** [review]
cli doc is great

**Review by ziausyed — APPROVED** [review]
nice! clean and well-written.

**Pull request merged**
